services:

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: Student-fee

    ports:
      - "3306:3306"

    volumes:
      - ./mysql-data:/var/lib/mysql

    networks:
      - springboot-mysql-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  springboot-app:
    build: .
    container_name: springboot-app

    ports:
      - "8091:8091"

    depends_on:
      mysql-container:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/Student-fee?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@123
      SERVER_PORT: 8091

    networks:
      - springboot-mysql-network

networks:
  springboot-mysql-network:
    name: springboot-mysql-network
